name: auto_construction
description: auto create from no parameters construction
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter